# Generated by Django 4.2.11 on 2024-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationprice',
            old_name='price',
            new_name='price_max',
        ),
        migrations.AddField(
            model_name='variationprice',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
