# Generated by Django 4.2.11 on 2024-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_variationprice_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationprice',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
